#!/bin/sh

set -e

CURRENT_PANE="$(tmux display-message -p -F "#{session_name}")"
if echo "$CURRENT_PANE" | grep -q '^popup.*'; then
    tmux detach-client
else
    if [ "$1" = "single" ]; then
        tmux popup -d '#{pane_current_path}' -x100% -y0% -w50% -h50% -CE "tmux attach -t 'popup-$CURRENT_PANE' || tmux new -s 'popup-$CURRENT_PANE'" || true
    else
        tmux popup -x100% -y0% -w50% -h50% "tmux attach -t floating || tmux new -s floating" || true
    fi
fi
